vt-braintree/vt-braintree/VT.Web/Models/CommissionsViewModel.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Amazon.EC2.Model;

namespace VT.Web.Models
{
    public class CommissionsViewModel
    {
        public DateTime Date { get; set; }
        public int ServiceRecordId { get; set; }
        public decimal Amount { get; set; }
        public string BtTransactionId { get; set; }
        public string Type { get; set; }
        public string CustomerName { get; set; }
        public string CompanyName { get; set; }
    }


    public class CommissionInputModel
    {
        public CommissionInputModel()
        {
            Customers = new List<int>();
        }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? CompanyId { get; set; }
        public List<int> Customers { get; set; }
        public string CompanyName { get; set; }
    }

    public class CommissionsInputModel
    {
        public CommissionsInputModel()
        {
            CompanyId = new List<int>();
        }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; } 
        public List<int> CompanyId { get; set; }
    }

    public class InvoicesViewModel
    {
        public DateTime InvoiceDate { get; set; }
        public int InvoiceNumber { get; set; }
        public string Customer { get; set; }
        public string CustomerEmail { get; set; }
        public decimal Amount { get; set; }
        public string PaymentType { get; set; }
        public DateTime ServiceDate { get; set; }
        public string TransactionId { get; set; }
    }

    public class CommissionExpenseViewModel
    {
        public DateTime Date { get; set; }
        public int CommissionId { get; set; }
        public string InvoiceNumber { get; set; }
        public decimal Amount { get; set; }
        public string TransactionId { get; set; }
        public string WhenCollected { get; set; }
    }

    public class VoidInvoicesViewModel
    {
        public DateTime? InvoiceDate { get; set; }
        public int InvoiceNumber { get; set; }
        public string Customer { get; set; }
        public string CustomerEmail { get; set; }
        public decimal Amount { get; set; }
        public string PaymentType { get; set; }
        public DateTime? VoidedOn { get; set; }
        public string Comments { get; set; } 
    }

    public class VoidInvoiceViewModel
    { 
        public int Id { get; set; }
        public string Organization { get; set; }
        public string Customer { get; set; }
        public string Employee { get; set; } 
        public DateTime? ServiceDate { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public string Status { get; set; }
        public int TotalAmount { get; set; }
        public int TransId { get; set; }
        public DateTime? VoidDate { get; set; }
    }
}

vt-braintree/vt-braintree/VT.Web/Controllers/AccountingController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using VT.Common;
using VT.Services.DTOs;
using VT.Services.Interfaces;
using VT.Web.Models;

namespace VT.Web.Controllers
{
    public class AccountingController : BaseController
    {
        #region Fields

        private readonly ICustomerService _customerService;
        private readonly ICompanyService _companyService;
        private readonly ICommissionService _commissionService;

        #endregion

        #region Constructor

        public AccountingController(ICustomerService customerService,
            ICompanyService companyService, 
            ICommissionService commissionService)
        {
            _customerService = customerService;
            _companyService = companyService;
            _commissionService = commissionService;
        }

        #endregion

        #region Action Method(s)

        // GET: Accounting
        public ActionResult UnPaidCommissions()
        {
            return View();
        }

        public ActionResult Commissions()
        {
            return View();
        }

        [Route("~/UnPaidServices")]
        public ActionResult UnPaidServices()
        {
            PopulateViewData();
             
            var model = new CommissionInputModel
            {
                CompanyId = CurrentIdentity.CompanyId,
                CompanyName = CurrentIdentity.CompanyName
            };
            return View(model);
        }

        [Route("~/Accounting/GetCustomers/{id}")]
        public JsonResult GetCustomers(int id)
        {
            var customers = GetCustomerList(id);
            return Json(customers, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Route("~/Accounting/GetUnpaidServices")]
        public ActionResult GetUnpaidServices()
        {
            return PartialView("UnpaidServicesGrid");
        }

        [Route("~/Accounting/GetUnpaidServicesList")]
        public ActionResult GetUnpaidServicesList([DataSourceRequest] DataSourceRequest request,
            DateTime? startDate, DateTime? endDate, int? companyId, List<int> customers)
        {
            var invoiceResponse = _commissionService.GetInvoiceDetails(new GetInvoiceDetailRequest
            {
                StartDate = startDate,
                EndDate = endDate,
                CompanyId = companyId,
                Customers = customers
            });

            var result = invoiceResponse.Items.Any() ? 
                Mapper.Map<List<InvoicesViewModel>>(invoiceResponse.Items) : 
                new List<InvoicesViewModel>();

            return Json(result.ToDataSourceResult(request));
        }


         [Route("~/Accounting/GetVoidInvoiceServicesList")]
        public ActionResult GetVoidInvoiceServicesList([DataSourceRequest] DataSourceRequest request,
            DateTime? startDate, DateTime? endDate, int? companyId, List<int> customers)
        {
            var voidInvoiceResponse = _commissionService.GetVoidInvoiceDetails(new GetVoidInvoiceDetailRequest()
            {
                StartDate = startDate,
                EndDate = endDate,
                CompanyId = companyId,
                Customers = customers
            });

            var result = voidInvoiceResponse.Items.Any() ? 
                Mapper.Map<List<VoidInvoicesViewModel>>(voidInvoiceResponse.Items) :
                new List<VoidInvoicesViewModel>();

            return Json(result.ToDataSourceResult(request));
        }
      



        [Route("~/Accounting/GetCommissionExpenseList")]
        public ActionResult GetCommissionExpenseList([DataSourceRequest] DataSourceRequest request, 
            DateTime? startDate, DateTime? endDate, int? companyId, List<int> customers)
        {
            var commissionExpenseResponse = _commissionService.GetCommissionExpenseDetails(new GetCommissionExpenseRequest
            {
                StartDate = startDate,
                EndDate = endDate,
                CompanyId = companyId,
                Customers = customers
            });

            var result = commissionExpenseResponse.Items.Any() ? 
                Mapper.Map<List<CommissionExpenseViewModel>>(commissionExpenseResponse.Items) : 
                new List<CommissionExpenseViewModel>();

            return Json(result.ToDataSourceResult(request));
        }

        [Route("~/Accounting/ExportInvoices")]
        public ActionResult ExportInvoices(DateTime startDate, DateTime endDate, 
            int? companyId, string companyName, string customers)
        {
            var customerList = GetIntIdsList(customers);

            var invoiceResponse = _commissionService.GetInvoiceDetails(new GetInvoiceDetailRequest
            {
                StartDate = startDate,
                EndDate = endDate,
                CompanyId = companyId,
                Customers = customerList
            });

            var result = invoiceResponse.Items.Any() ?
                Mapper.Map<List<InvoicesViewModel>>(invoiceResponse.Items) :
                new List<InvoicesViewModel>();

            var fileName =  string.Format("{0}_Invoices_{1}_to_{2}_on_{3}.csv", companyName,
                    startDate.ToString("MMddyyyy"), endDate.ToString("MMddyyyy"),
                    DateTime.UtcNow.ToString("MMddyyyy"));

            return CreateCsvFile(result, fileName);
        }


        [Route("~/Accounting/ExportVoidInvoices")]
        public ActionResult ExportVoidInvoices(DateTime startDate, DateTime endDate,
            int? companyId, string companyName, string customers)
        {
            var customerList = GetIntIdsList(customers);

            var voidinvoiceResponse = _commissionService.GetVoidInvoiceDetails(new GetVoidInvoiceDetailRequest
            {
                StartDate = startDate,
                EndDate = endDate,
                CompanyId = companyId,
                Customers = customerList
            });

            var result = voidinvoiceResponse.Items.Any() ?
                Mapper.Map<List<VoidInvoicesViewModel>>(voidinvoiceResponse.Items) :
                new List<VoidInvoicesViewModel>();

            var fileName = string.Format("{0}_VoidInvoices_{1}_to_{2}_on_{3}.csv", companyName,
                    startDate.ToString("MMddyyyy"), endDate.ToString("MMddyyyy"),
                    DateTime.UtcNow.ToString("MMddyyyy"));

            return CreateCsvFile(result, fileName);
        }



        [Route("~/Accounting/ExportCommission")]
        public ActionResult ExportCommission(DateTime startDate, DateTime endDate, 
            int? companyId, string companyName, string customers)
        {
            var customerList = GetIntIdsList(customers);

            var commissionExpenseResponse = _commissionService.GetCommissionExpenseDetails(new GetCommissionExpenseRequest
            {
                StartDate = startDate,
                EndDate = endDate,
                CompanyId = companyId,
                Customers = customerList
            });

            var result = commissionExpenseResponse.Items.Any() ?
                Mapper.Map<List<CommissionExpenseViewModel>>(commissionExpenseResponse.Items) :
                new List<CommissionExpenseViewModel>();

            var fileName = string.Format("{0}_Commissions_{1}_to_{2}_on_{3}.csv", companyName,
                    startDate.ToString("MMddyyyy"), endDate.ToString("MMddyyyy"),
                    DateTime.UtcNow.ToString("MMddyyyy"));

            return CreateCsvFile(result, fileName);
        }

        #endregion

        #region Private Method(s)

        private List<int> GetIntIdsList(string ids)
        {
            var customerList = new List<int>();

            if (!string.IsNullOrEmpty(ids))
            {
                var arr = ids.Replace("[", String.Empty).Replace("]", String.Empty).Split(',');
                foreach (var item in arr)
                {
                    int value;
                    if (Int32.TryParse(item, out value))
                        customerList.Add(value);
                }
            }
            return customerList;
        }

        private void PopulateViewData()
        {
            ViewData["Organizations"] = GetOrganizations();
            ViewData["Customers"] = new List<SelectListItem>();
        }

        private List<SelectListItem> GetOrganizations()
        {
            var companies = _companyService.GetOranizationList();
            var list = new List<SelectListItem> { new SelectListItem { Text = "--Select--", Value = "" } };
            list.AddRange(companies.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.CompanyId.ToString(CultureInfo.InvariantCulture)
            }));
            return list;
        }

        private List<SelectListItem> GetCustomerList(int? companyId)
        {
            if (companyId == null) return new List<SelectListItem>(); 

            var companies = _customerService.GetAllCustomers(companyId);
            var list = companies.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.CustomerId.ToString(CultureInfo.InvariantCulture),
                Selected = true
            }).ToList();

            var organiztions = new List<SelectListItem>
            {
                //new SelectListItem {Selected = true, Text = "All", Value = "0"},
            };

            organiztions.AddRange(list);

            return organiztions;
        }

        #endregion
    }
}

vt-braintree/vt-braintree/VT.Web/Controllers/CommissionsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using EO.Internal;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using VT.Common.Utils;
using VT.Services.DTOs;
using VT.Services.Interfaces;
using VT.Web.Models;

namespace VT.Web.Controllers
{
    public class CommissionsController : BaseController
    {
        #region Fields

        private readonly ICommissionService _commissionService;
        private readonly ICompanyService _companyService;

        #endregion

        #region Constructor

        public CommissionsController(ICommissionService commissionService, ICompanyService companyService)
        {
            _commissionService = commissionService;
            _companyService = companyService;
        }

        #endregion

        #region Action Method(s)

        [Route("~/Commissions")]
        public ActionResult Index()
        {
            PopulateViewData();
            return View();
        }

        [HttpPost]
        [Route("~/Commissions/GetCommissions")]
        public ActionResult GetUnpaidServices()
        {
            return PartialView("CommissionsGrid");
        }


        [HttpPost]
        [Route("~/Commissions/GetCommissionList")]
        public ActionResult GetCommissionList([DataSourceRequest] DataSourceRequest request,
            DateTime? startDate, DateTime? endDate, List<int> companyId)
        {
            var commissionExpenseResponse = _commissionService.GetCommissionsForSuperAdmin(new GetCommissionsRequest
            {
                StartDate = startDate,
                EndDate = endDate,
                CompanyId = companyId 
            });

            var result = commissionExpenseResponse.Items.Any() ?
                Mapper.Map<List<CommissionExpenseViewModel>>(commissionExpenseResponse.Items) :
                new List<CommissionExpenseViewModel>();

            return Json(result.ToDataSourceResult(request));
        }

        [Route("~/Commissions/ExportCommission")]
        public ActionResult ExportCommission(DateTime? startDate, DateTime? endDate, string companyId)
        {
            var companies = GetIntIdsList(companyId);

            var commissionExpenseResponse = _commissionService.GetCommissionsForSuperAdmin(new GetCommissionsRequest
            {
                StartDate = startDate,
                EndDate = endDate,
                CompanyId = companies, 
            });

            var result = commissionExpenseResponse.Items.Any() ?
                Mapper.Map<List<CommissionExpenseViewModel>>(commissionExpenseResponse.Items) :
                new List<CommissionExpenseViewModel>();

            var fileName = string.Format("CommissionCollected_{0}_to_{1}_on_{2}.csv",
                startDate.Value.ToString("MMddyyyy"), endDate.Value.ToString("MMddyyyy"),
                DateTime.UtcNow.ToString("MMddyyyy"));

            return CreateCsvFile(result, fileName);
        }

        [Route("~/Commissions/GetOrganizations")]
        public JsonResult GetOrganizations()
        {
            var companies = _companyService.GetOranizationList();
            var list = companies.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.CompanyId.ToString(CultureInfo.InvariantCulture),
                Selected = true
            }).ToList(); 
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        private List<int> GetIntIdsList(string ids)
        {
            var customerList = new List<int>();

            if (!string.IsNullOrEmpty(ids))
            {
                var arr = ids.Replace("[", String.Empty).Replace("]", String.Empty).Split(',');
                foreach (var item in arr)
                {
                    int value;
                    if (Int32.TryParse(item, out value))
                        customerList.Add(value);
                }
            }
            return customerList;
        }

        #endregion

        #region Private Method(s)
         
        private void PopulateViewData()
        {
            ViewData["Organizations"] = new List<SelectListItem>(); 
        }
         
         
        #endregion
    }
}

vt-braintree/vt-braintree/VT.Web/Views/Accounting/Commissions.cshtml
@using Kendo.Mvc.UI
@using VT.Common
@using VT.Web.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LoggedInLayout.cshtml"; 
}
 
@section PageLevelScripts
{
    <script type="text/javascript">
    </script>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>COMMISSIONS</h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>COMMISSIONS</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    
                    @Html.Partial("GridHeader", "CommissionListGrid")

                    @(Html.Kendo().Grid<CommissionsViewModel>()
                          .Name("CommissionListGrid")
                          .Pageable(page => page
                              .Info(true)
                              .ButtonCount(5)
                              .Messages(message => message
                                  .Empty("No data")
                                  .Next("Next")
                                  .Previous("Previous")
                                  .First("First")
                                  .Last("Last")
                              )
                          )
                          .Filterable()
                          .Sortable()
                          .Columns(columns =>
                          {

                          columns.Bound(o => o.ServiceRecordId).Title("Id")
                              .ClientTemplate("<a href='/Billing/Download/#= ServiceRecordId #'>#= ServiceRecordId # </a>")
                              .Width(75).Filterable(false);

                          columns.Bound(o => o.CustomerName).Title("Customer");
                          columns.Bound(o => o.CompanyName).Title("Organization").Visible(User.IsInRole(UserRoles.SuperAdmin.ToString()));
                          columns.Bound(o => o.Date).ClientTemplate("#= Date == null ? '' : kendo.toString(Date,'MM/dd/yyyy HH:mm')#").Title("Date");

                          columns.Bound(o => o.Amount).Title("Amount").Format("{0:c}");
                          columns.Bound(o => o.BtTransactionId).Title("Trans Id");

                          columns.Bound(o => o.Type).Title("Commission Type");
                         
                          })
                          .Events(events => events.DataBound("VT.Util.ConnectKendoGrids"))
                          .DataSource(dataSource => dataSource
                              .Ajax()
                              .PageSize(10)
                              .Model(model => model.Id(p => p.ServiceRecordId))
                              .Read(read => read.Action("GetCommissions", "Commissions"))
                          ))
                </div>
            </div>
        </div>
    </div>
</div>

vt-braintree/vt-braintree/VT.Web/Views/Accounting/UnpaidCommissions.cshtml
@using Kendo.Mvc.UI
@using VT.Common
@using VT.Web.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LoggedInLayout.cshtml"; 
}
 
@section PageLevelScripts
{
    <script type="text/javascript">
    </script>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>UNPAID COMMISSIONS</h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>UNPAID COMMISSIONS</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>

vt-braintree/vt-braintree/VT.Web/Views/Accounting/UnpaidServices.cshtml
@using Kendo.Mvc.UI
@using VT.Common
@using VT.Web.Models
@model CommissionInputModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LoggedInLayout.cshtml";
}

@section PageLevelStyles{
    <link href="~/Content/plugins/datapicker/datepicker3.css" rel="stylesheet"/>
    <link href="~/Content/plugins/chosen/chosen.css" rel="stylesheet" />
}

@section PageLevelScripts
{
    <script src="~/Scripts/plugins/chosen/chosen.jquery.js"></script>
    <script src="~/Scripts/plugins/datapicker/bootstrap-datepicker.js"></script>
    @Scripts.Render("~/plugins/validate")
    @Scripts.Render("~/plugins/iCheck")

    <script type="text/javascript">

        $('.input-group.date').datepicker({
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            autoclose: true
        });

        var refreshList = function(id, data) {

            $(id).empty().prepend("<option value=''></option>").val('').trigger("liszt:updated");

            $.each(data, function(index, item) {
                $(id).append($('<option>',
                {
                    value: item.Value,
                    text: item.Text,
                    selected: item.Selected
                }));
            });

            $(id).chosen({ width: "95%" });
        };

        var fillCustomers = function(val) {
            $.ajax({
                url: '/Accounting/GetCustomers/' + val,
                type: 'GET',
                success: function (data) {
                    $("#data_3").removeClass("hide");
                    refreshList("#Customers", data);
                    return false;
                }
            });
        };

        $("#CompanyId").change(function() {
            var val = $(this).val();
            if (val == '' || val == "-1") {
                return false;
            }


            var companyName = $("#CompanyId option:selected").text();
            $("#CompanyName").val(companyName);

            fillCustomers(val);
        });

        @if (User.IsInRole(UserRoles.CompanyAdmin.ToString()))
        {
            @:fillCustomers($("#CompanyId").val());
        }

        // Unpaid Services
        var unpaidServicesForm = $("#formUnpaidServices").validate({
            rules: {
                StartDate: {
                    required: true
                },
                CompanyId: {
                    required: true
                },
                EndDate: {
                    required: true
                },
                Customers : {
                    required: true
                }
            },
            highlight: function (label) {
                $(label).closest('.form-group').removeClass('has-success').addClass('has-error');
            },
            success: function (label) {
                $(label).closest('.form-group').removeClass('has-error');
                label.remove();
            },
            errorPlacement: function (error, element) {
                var placement = element.closest('.input-group');
                if (!placement.get(0)) {
                    placement = element;
                }
                if (error.text() !== '') {
                    placement.after(error);
                }
            },
            submitHandler: function (form) {
                var buttonText = $("#btnRunReport").html();

                $("#btnRunReport").attr('disabled', '').html('<i class="fa fa-spinner fa-spin"></i>&nbsp; ' + buttonText);

                $(form).ajaxSubmit({
                    success: function (data) {
                        if (data) {
                            $("#results").html(data);
                        } else {
                            VT.Util.Notification(false, "Some error occured.");
                        }
                        $("#btnRunReport").attr('disabled', null).html(buttonText);
                    },
                    error: function (xhr, status, error) {
                        $("#btnRunReport").attr('disabled', null).html(buttonText);
                    }
                });
                return false;
            }
        });

    </script>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>INCOME & EXPENSE</h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>INCOME & EXPENSE</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form id="formUnpaidServices" action="@Url.Action("GetUnpaidServices","Accounting")" method="POST">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group" id="data_1">
                                    <label class="font-noraml">Start Date</label>
                                    <div class="input-group date">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        @Html.TextBoxFor(x => x.StartDate, new {@class = "form-control"})
                                    </div>
                                </div>

                                @if (User.IsInRole(UserRoles.SuperAdmin.ToString()))
                                {
                                    <div class="form-group" id="data_4">
                                        <label class="font-noraml">Organization</label>
                                        <div class="input-group">
                                            @Html.DropDownListFor(x => x.CompanyId, ViewData["Organizations"] as IEnumerable<SelectListItem>, new {@class = "form-control"})
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    @Html.HiddenFor(x => x.CompanyId)
                                }
                                @Html.HiddenFor(x => x.CompanyName)
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group" id="data_2">
                                    <label class="font-noraml">End Date</label>
                                    <div class="input-group date">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        @Html.TextBoxFor(x => x.EndDate, new {@class = "form-control"})
                                    </div>
                                </div>
                                <div class="form-group hidden" id="data_3">
                                    <label class="font-noraml">Customers</label>
                                    <div class="input-group">
                                        @Html.DropDownListFor(x => x.Customers, ViewData["Customers"] as IEnumerable<SelectListItem>, new {@class = "chosen-select", multiple = "multiple"})
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <input id="btnRunReport" type="submit" value="Run Report" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="row" id="results">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>