vt-braintree/vt-braintree/VT.Web/Controllers/CompanyServicesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using VT.Common.Utils;
using VT.Data;
using VT.Services.Interfaces;
using VT.Web.Models;
using VT.Services.DTOs;
using System.Globalization;

namespace VT.Web.Controllers
{
    public class CompanyServicesController : BaseController
    {
        #region Fields

        private readonly ICompanyServiceService _companyServiceService;
        private readonly ICompanyService _companyService;
        private readonly IServiceRecordService _serviceRecordService;
        private readonly IServiceRecordItemService _serviceRecordItemService;

        #endregion

        #region Constructor

        public CompanyServicesController(ICompanyServiceService companyServiceService,
            ICompanyService companyService, IServiceRecordService serviceRecordService,
            IServiceRecordItemService serviceRecordItemService) 
        {
            _companyServiceService = companyServiceService;
            _companyService = companyService;
            _serviceRecordService = serviceRecordService;
            _serviceRecordItemService = serviceRecordItemService; 
        }

        #endregion

        #region Action Method(s)

        [HttpGet]
        [Route("~/CompanyServices")]
        public ActionResult Index()
        {
            PopulateViews();
            return View();
        }

        [HttpPost]
        [Route("~/CompanyServices/DeleteCompanyServices")]
        public ActionResult DeleteCompanyServices(DeleteUsersViewModel model)
        {
            var response = _companyServiceService.DeleteCompanyServices(model.Ids);
            return Json(new
            {
                success = response.Success,
                message = response.Message
            });
        }

        [HttpPost]
        [Route("~/CompanyServices/GetCompanyService/{id}")]
        public ActionResult GetCompanyService(int id)
        {
            var companyService = _companyServiceService.GetCompanyService(id);
            if (companyService == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Company service does not exist in the database."
                });
            }
            var model = new CompanyServiceListViewModel
            {
                Id = companyService.CompanyServiceId,
                Name = companyService.Name,
                Description = companyService.Description,
                CompanyId = companyService.CompanyId
            };
            return Json(new
            {
                success = true,
                message = string.Empty,
                cs = model
            });
        }

        [HttpPost]
        [Route("~/CompanyServices/GetCompanyServiceDetail/{id}")]
        public ActionResult GetCompanyServiceDetail(int id)
        {
            var companyService = _companyServiceService.GetCompanyService(id);
            if (companyService == null)
            {
                return Json(new
                {
                    success = false,
                    message = "Company service does not exist in the database."
                });
            }
            var model = new CompanyServiceListViewModel
            {
                Id = companyService.CompanyServiceId,
                Name = companyService.Name,
                Description = companyService.Description,
                CompanyId = companyService.CompanyId
            };
            return PartialView("CompanyServiceDetail", model);
        }

        [HttpPost]
        [Route("~/CompanyServices/CompanyServiceList")]
        public ActionResult CompanyServiceList([DataSourceRequest] DataSourceRequest request)
        {
            var data = GetCompanyServiceList().ToList();
            return Json(data.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Route("~/CompanyServices/SaveCompanyService")]
        public ActionResult SaveCompanyService(SaveCompanyServiceModel model)
        {
            var response = _companyServiceService.SaveCompanyService(new SaveCompanyServiceRequest
            {
                CompanyServiceId = model.CompanyServiceId,
                CompanyId = model.CompanyId != null ? model.CompanyId.Value : 0, //TODO: CompanyId can be nullable here            
                Name = model.Name,
                Description = model.Description
            });

            return Json(new
            {
                success = response.Success,
                message = response.Message
            });
        }

        [HttpPost]
        [Route("~/CompanyServices/ServiceRecords/{id}")]
        public ActionResult ServiceRecords(int id, [DataSourceRequest] DataSourceRequest request)
        {
            var data = GetServiceRecordList(id).ToList();
            return Json(data.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Route("~/CompanyServices/ServiceRecordItems/{id}")]
        public ActionResult ServiceRecordItems(int id, int companyServiceId, [DataSourceRequest] DataSourceRequest request)
        {
            var data = GetServiceRecordItemList(id, companyServiceId).ToList();
            return Json(data.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Private Methods

        private IEnumerable<ServiceRecordDetail> GetServiceRecordList(int id)
        {
            var list = _serviceRecordService.GetServiceRecordsByCompanyService(id);
            var result = list.Select(x => new ServiceRecordDetail
            {
                BilledToCompany = x.BilledToCompany,
                CompanyId = x.CompanyId,
                CompanyName = x.Company != null ? x.Company.Name : "N/A",
                CompanyWorkerEmail = string.Format("{0} {1} ({2})", x.CompanyWorker.FirstName, x.CompanyWorker.LastName, x.CompanyWorker.Email),
                CustomerId = x.CustomerId,
                CustomerName = x.Customer.Name,
                Description = x.Description,
                EndTime = x.EndTime,
                HasNonService = x.ServiceRecordItems.Any(y => y.CostOfService == null || y.CostOfService == 0),
                ServiceRecordId = x.ServiceRecordId,
                StartTime = x.StartTime,
                Status = EnumUtil.GetDescription(x.Status),
                TotalAmount = x.TotalAmount
            }).ToList();
            return result;
        }

        private IEnumerable<ServiceRecordItemDetail> GetServiceRecordItemList(int id, int? companyServiceId)
        {
            var list = _serviceRecordItemService.GetRecordItems(id);
            var result = list.Select(x => new ServiceRecordItemDetail
            {
                CompanyServiceId = x.CompanyServiceId !=null ? x.CompanyServiceId.Value : 0,
                CostOfService = x.CostOfService,
                ServiceName = x.ServiceName,
                CustomerId = x.CustomerId,
                EndTime = x.EndTime,
                Description = x.Description,
                ServiceRecordId = x.ServiceRecordId,
                StartTime = x.StartTime,
                ServiceRecordItemId = x.ServiceRecordItemId,
                Type = EnumUtil.GetDescription(x.Type),
            }).ToList();
            return result;
        }

        private IEnumerable<CompanyServiceListViewModel> GetCompanyServiceList()
        {
            var companies = _companyServiceService.GetAllCompanyServices(CurrentIdentity.CompanyId);
            var list = companies.Select(x => new CompanyServiceListViewModel
            {
                Id = x.CompanyServiceId,
                CompanyName = x.Company.Name,
                Name = x.Name,
                Description = x.Description,
                CompanyId = x.CompanyId
            }).ToList();
            return list;
        }

        private void PopulateViews()
        {
            var companies = _companyService.GetOranizationList();
            var list = new List<SelectListItem> { new SelectListItem { Text = "--Select--", Value = "" } };
            list.AddRange(companies.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.CompanyId.ToString(CultureInfo.InvariantCulture)
            }));
            ViewData["Organizations"] = list;
        }

        #endregion

    }
}

vt-braintree/vt-braintree/VT.Web/Views/CompanyServices/AddCompanyService.cshtml
@using VT.Common
@model VT.Web.Models.SaveCompanyServiceModel
<div id="modal-add-cs-form" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <form id="saveCompanyServiceForm" action="@Url.Action("SaveCompanyService", "CompanyServices")" class="form-horizontal" method="POST" role="form">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="modal-save-cs-title">Add Company Service</h4>
                    <small class="font-bold"></small>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12">
                            @Html.HiddenFor(x => x.CompanyServiceId)
                            @if (User.IsInRole(UserRoles.SuperAdmin.ToString()))
                            {
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">Organization</label>
                                    <div class="col-sm-9">
                                        @Html.DropDownListFor(x => x.CompanyId, ViewData["Organizations"] as IEnumerable<SelectListItem>, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="hr-line-dashed"></div>
                            }
                            else
                            {
                                @Html.HiddenFor(x => x.CompanyId)
                            }
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Name</label>
                                <div class="col-sm-9">
                                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control small" })
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Description</label>
                                <div class="col-sm-9">
                                    @Html.TextAreaFor(x => x.Description, new { @class = "form-control small" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button id="btnSaveCompanyService" type="submit" class="btn btn-warning">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

vt-braintree/vt-braintree/VT.Web/Views/CompanyServices/CompanyServiceDetail.cshtml
@using Kendo.Mvc.UI
@using VT.Common
@model VT.Web.Models.CompanyServiceListViewModel

<script type="text/javascript">
    function getImageInfo(item) {
        return [
            "<a class='attachment' data-id='" + item.ServiceRecordItemId + "' href='#' title='View Images'><i class='fa fa-camera'></i></a>"
        ].join('');
    }

    $(document).on("click", ".attachment", function () {
        $.ajax({
            url: "/ServiceRecords/Attachments/" + $(this).data("id"),
            type: "POST",
            success: function (viewResult) {
                $("#divAttachments").html(viewResult);
                $("#modal-attachments").modal({
                    backdrop: 'static',
                    keyboard: false,
                    show: true
                });
            }
        });
        return false;
    });
</script>

<div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInUp">
        <div class="ibox">
            <div class="ibox-content">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="m-b-md">
                            <a class='btn btn-white btn-xs pull-right edit-companyservice' data-id='@Model.Id' href='#' title='Edit'>Edit Company Service</a>
                            <h2>Detail of "@(Model.Name)"  </h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-5">
                        <dl class="dl-horizontal">
                            <dt>Description:</dt>
                            <dd>@(Model.Description)</dd>
                        </dl>
                    </div>
                </div>
                <div class="row m-t-sm">
                    <div class="col-lg-12">
                        <div class="panel blank-panel">
                            <div class="panel-heading">
                                <div class="panel-options">
                                    <ul class="nav nav-tabs">
                                        <li class="active"><a data-toggle="tab" href="#tab-2">Service Activity</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="tab-content">
                                    <div id="tab-2" class="tab-pane active">
                                        @(Html.Kendo().Grid<VT.Web.Models.ServiceRecordDetail>()
                                                      .Name("ServiceRecordListGrid")
                                                      .Pageable(page => page
                                                        .Info(true)
                                                        .ButtonCount(5)
                                                        .Messages(message => message
                                                                                    .Empty("No data")
                                                                                    .Next("Next")
                                                                                    .Previous("Previous")
                                                                                    .First("First")
                                                                                    .Last("Last")
                                                        )
                                                      )
                                                      .Filterable()
                                                      .Sortable()
                                                      .Columns(columns =>
                                                               {
                                                                   columns.Bound(o => o.ServiceRecordId).Title("Id").Width(75);

                                                                   columns.Bound(o => o.CompanyName).Title("Organization").Visible(User.IsInRole(UserRoles.SuperAdmin.ToString()));
                                                                   columns.Bound(o => o.CustomerName).Title("Customer");
                                                                   columns.Bound(o => o.CompanyWorkerEmail).Title("Employee");
                                                                   columns.Bound(o => o.EndTime).ClientTemplate("#=kendo.toString(EndTime,'MM/dd/yyyy HH:mm')#").Title("Time");
                                                                   columns.Bound(o => o.Status).Title("Status");
                                                                   columns.Bound(o => o.TotalAmount).Title("Total Amount").Format("{0:c}");
                                                               })
                                                      .DataSource(dataSource => dataSource
                                                                                    .Ajax()
                                                                                    .PageSize(10)
                                                                                    .Model(model => model.Id(p => p.ServiceRecordId))
                                                                                    .Read(read => read.Action("ServiceRecords", "CompanyServices", new { id = Model.Id }))
                                                      )
                                                      .ClientDetailTemplateId("ServiceRecordItemListTemplate")
                                        )
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script id="ServiceRecordItemListTemplate" type="text/kendo-tmpl">
    @(Html.Kendo().Grid<VT.Web.Models.ServiceRecordItemDetail>()
            .Name("ServiceRecordItemListGrid_#=ServiceRecordId#")
            .HtmlAttributes(new { @class = "recordItems", @title = "Services Performed" })
            .Sortable()
            .Columns(columns =>
                    {
                        columns.Bound(o => o.ServiceRecordId).Title("Id").Visible(false);
                        columns.Bound(o => o.ServiceRecordItemId).Width(75).Visible(false); ;
                        columns.Bound(o => o.ServiceName).Title("Service").Width(200);
                        columns.Bound(o => o.Description).Title("Description").Width(500); 
                        columns.Bound(o => o.CostOfService).Title("Cost").Format("{0:c}").Width(75);
                        columns.Template(@<text></text>).Title("Actions")
                        .ClientTemplate("\\#= getImageInfo.apply(this, arguments) \\#").Width(75);

                    })
                    .DataSource(dataSource => dataSource
                        .Ajax()
                        .Model(model => model.Id(p => p.ServiceRecordItemId))
                        .Read(read => read.Action("ServiceRecordItems", "CompanyServices", new { id = "#=ServiceRecordId#", companyServiceId = Model.Id }))
                    ).ToClientTemplate())
</script>

<script type="text/javascript">
    $(function() {
        $('#ServiceRecordListGrid').data('kendoGrid');
    })
</script> 

vt-braintree/vt-braintree/VT.Web/Views/CompanyServices/Index.cshtml
@using Kendo.Mvc.UI
@using VT.Common
@using VT.Web.Models

@{
    ViewBag.Title = "Company Services";
    Layout = "~/Views/Shared/LoggedInLayout.cshtml";
    var customIdentity = (VT.Common.CustomIdentity)User.Identity;
}

@section PageLevelScripts
{
    @Scripts.Render("~/plugins/validate")
    @Scripts.Render("~/plugins/iCheck")
    <script src="@Url.Content("~/Scripts/app/companyservice.js")"></script>

    <script type="text/javascript">
        
        function getActionsInfo(item) {
            return [
                "<a class='edit-companyservice' data-id='" + item.Id + "' href='#dynamicModal'><i class='fa fa-edit'></i> </a>" +
                "<a class='view-companyservice' data-id='" + item.Id + "' href='#dynamicModal'><i class='fa fa-eye'></i> </a>"
            ].join('');
        }
    </script>
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>COMPANY SERVICES</h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>ALL COMPANY SERVICES</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="">
                        <a href="#modal-add-cs-form" data-toggle="modal" class="btn btn-info btn-rounded btn-outline "><i class="fa fa-plus"></i> &nbsp; Add Company Service</a>
                        <a href="#modal-del-cs-form" id="btnDeleteCs" class="btn btn-danger btn-rounded btn-outline"><i class="fa fa-trash"></i> &nbsp; Delete Company Service</a>
                    </div>

                    @Html.Partial("GridHeader", "CompanyServiceListGrid")

                    @(Html.Kendo().Grid<CompanyServiceListViewModel>()
                          .Name("CompanyServiceListGrid")
                          .Reorderable(x => x.Columns(true))
                          .Pageable(page => page
                              .Info(true)
                              .ButtonCount(5)
                              .Messages(message => message
                                  .Empty("No data")
                                  .Next("Next")
                                  .Previous("Previous")
                                  .First("First")
                                  .Last("Last")
                              )
                          )
                          .Sortable()
                          .Filterable()
                          .Columns(columns =>
                          {
                              columns.Bound(x => x.Id).Title("")
                                  .ClientTemplate("<input type='checkbox' value='#= Id #' class='i-checks'></input>").Filterable(false);

                              columns.Bound(x => x.CompanyId).Visible(false);
                              columns.Bound(x => x.CompanyName).Visible(User.IsInRole(UserRoles.SuperAdmin.ToString())).Title("Organization").Filterable(ftb => ftb.Multi(true));
                              columns.Bound(x => x.Name).Title("Name");

                              columns.Bound(x => x.Description).Title("Description");

                              columns.Template(@<text></text>)
                                  .Title("Actions")
                                  .ClientTemplate("#= getActionsInfo.apply(this, arguments) #");
                          })
                                  .Events(events => events.DataBound("VT.Util.ConnectKendoGrids"))
                                  .DataSource(dataSource => dataSource
                                      .Ajax()
                                      .PageSize(10)
                                      .Model(model => model.Id(p => p.Id))
                                      .Read(read => read.Action("CompanyServiceList", "CompanyServices")))
                    )

                    @Html.Partial("ConfirmModal", new ModalViewModal
                    {
                        Id = "modal-del-cs-form",
                        IsAlertModel = false,
                        Title = "Delete Company Service(s)",
                        Message = "Are you sure you want to delete the selected service(s)?"
                    })


                </div>
            </div>
        </div>
    </div>

    <div class="row" id="divcsDetails">

    </div>

</div>

@Html.Partial("AddCompanyService", new SaveCompanyServiceModel
{
    CompanyId = customIdentity.CompanyId
})

<div id="divAttachments">
    <!--Load dynamic content through ajax-->
</div>